title: Dennis Odoom # your name (or website title) here
logo: "/images/profile-pic.jpg?raw=true" # your photo (or logo) here
description: > # Data Engineer (remove <br> elements if you don't need line breaks)
  Data Engineer 
  <br><br>
  Transforming data into a format that can easily be analyzed.
   Developing, maintaining and testing data infrastructure for data generation
  <br><br>
  <a href="https://www.linkedin.com/in/dennis-miller-odoom/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal

